#ifndef _CONFIG_H_
#define _CONFIG_H_


#define PACKET_TTL 64
#define PACKET_TCP_WINSIZE 8192
#define PACKET_SIZE 64
#define PACKET_BATCH 64

#define DEVICE_MEMPOOL_RX_ELEMENTS 8192
#define DEVICE_MEMPOOL_TX_ELEMENTS 64
#define DEVICE_MEMPOOL_CACHE_SIZE 256



#endif
